<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Common Error</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4c3f1b3f-a758-439f-acd7-957daa03c4a7</testSuiteGuid>
   <testCaseLink>
      <guid>2252093b-7842-49ae-b1db-75ab990e6f45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RA Test Cases/Common Error/TC1_Application Under Test</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cb8ae8f-d1d4-4b66-8654-c2b967cda73b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d2fb27-b1a3-4e14-91b0-dd5fcbc307cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bae05aa-6d10-4e38-a108-a2201a741050</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RA Test Cases/Common Error/TC2_Test Script Issue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c78adf38-5369-4ded-9d53-d7c0ddb11e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ba57ab0-351a-46cf-9239-a23b112290c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce67e25c-5827-452e-9860-2a8a14c4a7d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RA Test Cases/Common Error/TC3_Test Data Issue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56034652-66fe-4341-9283-219ee59056db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbe56d70-0d11-494c-8a78-642ec31f96ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>154fa9a3-f8af-4cca-b08e-e77d48860af5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RA Test Cases/Common Error/TC4_Automation Issue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b131bd5-e510-44fd-8889-6221f92ee550</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03aee650-5559-4707-be16-eb53cc4937aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b47d6d57-43c3-4726-abdb-dc55e847b491</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RA Test Cases/Common Error/TC6_Environment Issue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>205d5ede-eab9-4c94-8013-9c0abecb5629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fbc48b0-fa4a-4441-810c-2403911d2ba0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
